apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: heartbeat-event-source
  namespace: myproject
spec:
  image: quay.io/openshift-knative/knative-eventing-sources-heartbeats:v0.5.0
  args: 
   - '--label="<3"'
   - '--period=400'
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
